// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sample_package_0428

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Zhaoh0428Client is the client API for Zhaoh0428 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Zhaoh0428Client interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type zhaoh0428Client struct {
	cc grpc.ClientConnInterface
}

func NewZhaoh0428Client(cc grpc.ClientConnInterface) Zhaoh0428Client {
	return &zhaoh0428Client{cc}
}

func (c *zhaoh0428Client) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/sample_module_0428.sample_package_0428.Zhaoh0428/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zhaoh0428Client) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module_0428.sample_package_0428.Zhaoh0428/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Zhaoh0428Server is the server API for Zhaoh0428 service.
// All implementations must embed UnimplementedZhaoh0428Server
// for forward compatibility
type Zhaoh0428Server interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedZhaoh0428Server()
}

// UnimplementedZhaoh0428Server must be embedded to have forward compatible implementations.
type UnimplementedZhaoh0428Server struct {
}

func (UnimplementedZhaoh0428Server) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedZhaoh0428Server) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedZhaoh0428Server) mustEmbedUnimplementedZhaoh0428Server() {}

// UnsafeZhaoh0428Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Zhaoh0428Server will
// result in compilation errors.
type UnsafeZhaoh0428Server interface {
	mustEmbedUnimplementedZhaoh0428Server()
}

func RegisterZhaoh0428Server(s grpc.ServiceRegistrar, srv Zhaoh0428Server) {
	s.RegisterService(&Zhaoh0428_ServiceDesc, srv)
}

func _Zhaoh0428_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0428Server).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0428.sample_package_0428.Zhaoh0428/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0428Server).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zhaoh0428_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0428Server).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0428.sample_package_0428.Zhaoh0428/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0428Server).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zhaoh0428_ServiceDesc is the grpc.ServiceDesc for Zhaoh0428 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zhaoh0428_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module_0428.sample_package_0428.Zhaoh0428",
	HandlerType: (*Zhaoh0428Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _Zhaoh0428_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _Zhaoh0428_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Zhaoh0428.proto",
}
